/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package solomonClientLib;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author bwormley
 */
public class GameStatus extends javax.swing.JFrame {

    /**
     * Creates new form GameStatus
     */
    public GameStatus() {
        initComponents();
    }
    
    public GameStatus( String myName, String opponentName, int maxNumberOfRounds ) {
        initComponents();
        jMatchLabel.setText( String.format( "%s vs %s", myName, opponentName) );
        jMatchProgressBar.setMinimum(0);
        jMatchProgressBar.setMaximum(maxNumberOfRounds);
        this.maxNumberOfRounds = maxNumberOfRounds;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jMatchProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMatchLabel = new javax.swing.JLabel();
        jAbort = new javax.swing.JButton();
        jScorePanel = new javax.swing.JPanel();
        jScoreText = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMatchProgressBar.setStringPainted(true);

        jLabel1.setText("Match progress");

        jLabel2.setText("Running Score");

        jMatchLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMatchLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMatchLabel.setText("Match between LOCAL AI and REMOTE");

        jAbort.setText("Cancel");
        jAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbortActionPerformed(evt);
            }
        });

        jScorePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScoreText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScoreText.setText("score text");

        org.jdesktop.layout.GroupLayout jScorePanelLayout = new org.jdesktop.layout.GroupLayout(jScorePanel);
        jScorePanel.setLayout(jScorePanelLayout);
        jScorePanelLayout.setHorizontalGroup(
            jScorePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScoreText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );
        jScorePanelLayout.setVerticalGroup(
            jScorePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScorePanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jScoreText)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jAbort)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(20, 20, 20)
                            .add(jMatchLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 429, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(20, 20, 20)
                            .add(jLabel1))
                        .add(layout.createSequentialGroup()
                            .add(54, 54, 54)
                            .add(jMatchProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 398, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(23, 23, 23)
                            .add(jLabel2))
                        .add(layout.createSequentialGroup()
                            .add(50, 50, 50)
                            .add(jScorePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jMatchLabel)
                .add(18, 18, 18)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(jMatchProgressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScorePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(23, 23, 23)
                .add(jAbort)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jMatchProgressBar.getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbortActionPerformed
        this.dispose();
    }//GEN-LAST:event_jAbortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GameStatus().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAbort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMatchLabel;
    private javax.swing.JProgressBar jMatchProgressBar;
    private javax.swing.JPanel jScorePanel;
    private javax.swing.JLabel jScoreText;
    // End of variables declaration//GEN-END:variables


    /**
     * update status
     * 
     * @param rounds number of rounds played
     */
    private int maxNumberOfRounds;
    public void updateProgress( int rounds, int wins, int ties, int losses  ) {
        
        // update progress bar
        jMatchProgressBar.setString(
                String.format(
                    "Round %s of %s    (%2.0f%%)",
                    rounds,
                    maxNumberOfRounds,
                    ((rounds*1.0)/(maxNumberOfRounds*1.0))*100.0 ) );
        this.jMatchProgressBar.setValue( rounds );
        
        // update score bar
        int width  = jScorePanel.getWidth();
        int height = jScorePanel.getHeight();
        int myWinningWidth       = (int)((wins*1.0)/(rounds*1.0)*width);
        int opponentWinningWidth = (int)((losses*1.0)/(rounds*1.0)*width);
        Graphics2D gcx = (Graphics2D)jScorePanel.getGraphics();
        gcx.setColor(Color.YELLOW);
        gcx.fillRect( 0, 0, width, height );
        if (myWinningWidth>0) {
            gcx.setColor(Color.GREEN);
            gcx.fillRect( 0, 0, myWinningWidth, height );
        }
        if (opponentWinningWidth>0) {
            gcx.setColor(Color.RED);
            gcx.fillRect( width-opponentWinningWidth, 0, opponentWinningWidth, height );
        }
        jScoreText.setText( String.format( "%d Wins   %d Ties   %d Losses", wins, ties, losses ) );
    }
}
